jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

security:
  oauth2:
    client:
      clientId: ENC(f377virfMauTS5MCxDwcxcOQ85PCZuao)
      clientSecret: ENC(zooZz8CVgscSfuaG6OUQsDG2yNAES5+oSvibel+IR0kRwVbF3Hfw6wgrXEJ208Sr)
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me